In [1]:
import numpy as np

w1,w2,w3=0.2,0.4,0.5
kanto=np.array([74,66,45])
weights=np.array([w1,w2,w3])
print(np.dot(kanto,weights))

63.7


In [2]:
climate_data=np.array([[74,66,45],
                       [91,88,64],
                       [87,134,58],
                       [102,43,37],
                       [69,96,70]])
print(np.matmul(climate_data,weights))
print(climate_data@weights)
# Mathematics: np.sum, np.exp, np.round, arithmetic operators
# Array Manipulation: np.reshape, np.stack, np.concatenate, np.split
# Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
# Statistics: np.mean, np.median, np.std, np.max

[ 63.7  85.4 100.   56.1  87.2]
[ 63.7  85.4 100.   56.1  87.2]


In [3]:
arr2=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,1,2,3]])
arr3=np.array([[11,12,13,14],
              [15,16,17,18],
              [19,11,12,13]])
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [4]:
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [5]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [6]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [7]:
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [8]:
arr2%4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [9]:
arr2.shape

(3, 4)

In [10]:
arr4=np.array([4,5,6,7])
arr4.shape

(4,)

In [11]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [12]:
arr4_replicated=np.array([[4,5,6,7],
                          [4,5,6,7],
                          [4,5,6,7]])
arr2+arr4_replicated

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [13]:
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([[2,2,3],[1,2,5]])
arr1==arr2

array([[False,  True,  True],
       [False, False,  True]])

In [14]:
arr1!=arr2

array([[ True, False, False],
       [ True,  True, False]])

In [15]:
arr1>=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [16]:
arr1<arr2

array([[ True, False, False],
       [False, False, False]])

In [17]:
(arr1==arr2).sum()

np.int64(3)

In [18]:
arr3=np.array([[[11,12,13,14],
                [13,14,15,19]],

                [[15,16,17,21],
                 [63,92,36,18]],

                 [[98,32,81,23],
                  [17,18,19.5,43]]])
arr3.shape

(3, 2, 4)

In [19]:
arr3[1,1,2]

np.float64(36.0)

In [20]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [21]:
arr3[1:,1,3]

array([18., 43.])

In [22]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [25]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])